### ISSUE TITLE
Update theme to the latest version.

### ISSUE THREAD

**Issue by arshubham** [flathub/org.gtk.Gtk3theme.elementary#1]
It seems like the theme has not been updated in a long time. This is still using 5.1.1 tag which was created on Sep 25, 2017.

**Comment by TingPing** [comment]
@cassidyjames What happened to making  a new tag?

**Comment by cassidyjames** [comment]
@TingPing there has been pretty heavy work on the stylesheet since GUADEC, so a new release didn't really make sense in the middle of all of that. I'll talk to the team again and make sure we do that once it's settled. In the meantime, pointing to the latest commit is probably not the worst thing, though be aware master has dropped support for GTK3 < 3.20.

**Comment by TingPing** [comment]
The extension point is for Gtk 3.22 only.

You have commit access here if you want to bump the hash (and remove the branch): https://github.com/flathub/org.gtk.Gtk3theme.elementary/blob/master/org.gtk.Gtk3theme.elementary.json#L23-L24
